import type { DashboardPayload } from "../types/dashboard";

export const mockDashboardData: DashboardPayload = {
  generated_at: "2026-06-14",
  totals: {
    articles: 17,
    news: 9,
    projects: 14,
    stars: 633146,
    reports: 5,
  },
  dashboard: {
    articles: [
      {
        id: "article-1",
        type: "articles",
        title: "EvoArena: Tracking Memory Evolution for Robust LLM Agents",
        summary:
          "A benchmark and memory paradigm for evaluating LLM agents in dynamic environments.",
        url: "http://arxiv.org/abs/2606.13681v1",
        date: "2026-06-14",
        tags: ["Agent", "Memory"],
        order: 1,
      },
      {
        id: "article-2",
        type: "articles",
        title: "Learning to Reason by Analogy via Retrieval-Augmented Fine-Tuning",
        summary:
          "A retrieval-augmented reinforcement fine-tuning method for analogy-based reasoning.",
        url: "http://arxiv.org/abs/2606.13680v1",
        date: "2026-06-14",
        tags: ["RAG", "Reasoning"],
        order: 2,
      },
      {
        id: "article-3",
        type: "articles",
        title: "InterleaveThinker: Reinforcing Agentic Interleaved Generation",
        summary:
          "A multi-agent generation pipeline for planning, critique, and visual narrative refinement.",
        url: "http://arxiv.org/abs/2606.13679v1",
        date: "2026-06-14",
        tags: ["Agent", "Multimodal"],
        order: 3,
      },
      {
        id: "article-4",
        type: "articles",
        title: "Modality Forcing for Scalable Spatial Generation",
        summary:
          "A scalable approach for joint image-depth generation using sparse depth data.",
        url: "http://arxiv.org/abs/2606.13676v1",
        date: "2026-06-14",
        tags: ["Multimodal", "Generation"],
        order: 4,
      },
    ],
    news: [
      {
        id: "news-1",
        type: "news",
        title: "OpenAI announces new product and research updates",
        summary: "Recent OpenAI updates point to faster model iteration and broader product integration.",
        url: "https://openai.com/news/",
        date: "2026-06-14",
        source: "OpenAI News",
        tags: ["AI News"],
        order: 1,
      },
      {
        id: "news-2",
        type: "news",
        title: "DeepMind shares progress on AI systems",
        summary: "Research updates show continued work on models, agents, and scientific AI systems.",
        url: "https://deepmind.google/blog/",
        date: "2026-06-14",
        source: "Google DeepMind Blog",
        tags: ["Research"],
        order: 2,
      },
      {
        id: "news-3",
        type: "news",
        title: "NVIDIA expands AI infrastructure updates",
        summary: "Hardware and software updates continue to shape the AI developer stack.",
        url: "https://blogs.nvidia.com/",
        date: "2026-06-14",
        source: "NVIDIA Blog",
        tags: ["Infrastructure"],
        order: 3,
      },
    ],
    projects: [
      {
        id: "project-1",
        type: "projects",
        title: "mlabonne/llm-course",
        summary: "A structured course for learning LLM fundamentals, fine-tuning, and applications.",
        url: "https://github.com/mlabonne/llm-course",
        date: "2026-06-14",
        stars: 80113,
        language: "Python",
        tags: ["LLM", "Learning"],
        order: 1,
      },
      {
        id: "project-2",
        type: "projects",
        title: "lm-sys/FastChat",
        summary: "An open platform for training, serving, and evaluating chat models.",
        url: "https://github.com/lm-sys/FastChat",
        date: "2026-06-14",
        stars: 39470,
        language: "Python",
        tags: ["LLM", "Serving"],
        order: 2,
      },
      {
        id: "project-3",
        type: "projects",
        title: "HandsOnLLM/Hands-On-Large-Language-Models",
        summary: "Code examples and notebooks for practical large language model applications.",
        url: "https://github.com/HandsOnLLM/Hands-On-Large-Language-Models",
        date: "2026-06-14",
        stars: 26981,
        language: "Jupyter Notebook",
        tags: ["LLM", "Education", "Multimodal"],
        order: 3,
      },
      {
        id: "project-4",
        type: "projects",
        title: "langchain-ai/langchain",
        summary: "A framework for building context-aware LLM applications and agent workflows.",
        url: "https://github.com/langchain-ai/langchain",
        date: "2026-06-14",
        stars: 87200,
        language: "Python",
        tags: ["LLM", "Agent", "LangChain"],
        order: 4,
      },
    ],
  },
  history: {
    articles: [],
    news: [],
    projects: [],
  },
};

mockDashboardData.history = {
  articles: [
    ...mockDashboardData.dashboard.articles,
    ...Array.from({ length: 9 }, (_, index) => ({
      ...mockDashboardData.dashboard.articles[index % 4],
      id: `article-history-${index + 1}`,
      title: `${mockDashboardData.dashboard.articles[index % 4].title} (${index + 1})`,
      date: `2026-06-${String(13 - Math.floor(index / 3)).padStart(2, "0")}`,
      order: index + 5,
    })),
  ],
  news: [
    ...mockDashboardData.dashboard.news,
    ...Array.from({ length: 8 }, (_, index) => ({
      ...mockDashboardData.dashboard.news[index % 3],
      id: `news-history-${index + 1}`,
      title: `${mockDashboardData.dashboard.news[index % 3].title} (${index + 1})`,
      date: `2026-06-${String(13 - Math.floor(index / 2)).padStart(2, "0")}`,
      order: index + 4,
    })),
  ],
  projects: [
    ...mockDashboardData.dashboard.projects,
    ...Array.from({ length: 8 }, (_, index) => ({
      ...mockDashboardData.dashboard.projects[index % 4],
      id: `project-history-${index + 1}`,
      title: `${mockDashboardData.dashboard.projects[index % 4].title} (${index + 1})`,
      date: `2026-06-${String(13 - Math.floor(index / 2)).padStart(2, "0")}`,
      order: index + 5,
    })),
  ],
};
