"""Repository selection and summarization helpers."""

import json
import os
from typing import Any

from dotenv import load_dotenv

from config import (
    AI_KEYWORDS,
    BASE_DIR,
    OPENAI_GITHUB_SELECTION_MODEL,
    OPENAI_GITHUB_SUMMARY_MODEL,
)
from tools.github_tool import fetch_repository_readme


GITHUB_SUMMARY_FALLBACK = "待配置 OPENAI_API_KEY 后生成 GitHub 项目中文摘要。"
GITHUB_SUMMARY_FIELDS = [
    "one_sentence_summary",
    "chinese_summary",
    "main_features",
    "chinese_main_features",
    "technical_highlights",
    "chinese_technical_highlights",
    "learning_value",
    "chinese_learning_value",
    "recommended_for",
    "chinese_recommended_for",
    "possible_use_cases",
    "chinese_possible_use_cases",
]
GITHUB_SELECTION_PROMPT_FALLBACK = (
    "Select the top AI GitHub repositories for a daily intelligence report.\n"
    "Prioritize relevance to LLMs, AI agents, RAG, multimodal AI, AI coding, "
    "practical usefulness, learning value, project quality, and popularity.\n"
    "Return JSON only with this schema: {{\"selected_indices\": [0, 1]}}.\n"
    "Select at most {top_k} repositories.\n\n"
    "Candidate repositories:\n{repos}"
)
GITHUB_SUMMARY_PROMPT_FALLBACK = (
    "Summarize this AI GitHub repository for developers and AI learners.\n"
    "Return JSON only with these string fields:\n"
    "one_sentence_summary, chinese_summary, main_features, chinese_main_features, "
    "technical_highlights, chinese_technical_highlights, learning_value, "
    "chinese_learning_value, recommended_for, chinese_recommended_for, "
    "possible_use_cases, chinese_possible_use_cases.\n"
    "Do not merely repeat the description. If information is insufficient, say so "
    "instead of inventing details. Chinese fields should be natural Simplified "
    "Chinese sentences; keep repository names, library names, product names, model "
    "names, CLI commands, URLs, and common AI terms such as LLM, RAG, RL, VLM, "
    "Transformer in English when that is clearer.\n\n"
    "Repository name: {name}\n"
    "Description: {description}\n"
    "Stars: {stars}\n"
    "Language: {language}\n"
    "Topics: {topics}\n"
    "Homepage: {homepage}\n"
    "License: {license}\n"
    "URL: {url}\n\n"
    "README excerpt:\n{readme_excerpt}"
)


def select_important_repositories(
    repos: list[dict[str, Any]],
    top_k: int = 3,
) -> list[dict[str, Any]]:
    """Select the most useful repositories for the daily report."""
    if not repos or top_k <= 0:
        return []

    api_key = _get_openai_api_key()
    if api_key:
        selected_repos = _select_repositories_with_openai(repos, top_k, api_key)
        if selected_repos:
            return selected_repos

    return _select_repositories_with_local_score(repos, top_k)


def summarize_repository(repo: dict[str, Any]) -> dict[str, Any]:
    """Return a structured summary for one repository."""
    name = str(repo.get("name", "Unnamed repository"))
    description = str(
        repo.get("description", "Repository summary will be generated by the LLM.")
    )

    api_key = _get_openai_api_key()
    if api_key:
        llm_summary = _summarize_repository_with_openai(repo, api_key)
        if llm_summary:
            return _merge_repository_summary(repo, llm_summary)

    return {
        "name": name,
        "one_sentence_summary": description,
        "chinese_summary": GITHUB_SUMMARY_FALLBACK,
        "main_features": description or "TBD",
        "chinese_main_features": "待配置 OPENAI_API_KEY 后生成中文主要功能。",
        "technical_highlights": "TBD",
        "chinese_technical_highlights": "待配置 OPENAI_API_KEY 后生成中文技术亮点。",
        "learning_value": "TBD",
        "chinese_learning_value": "待配置 OPENAI_API_KEY 后生成中文学习价值。",
        "recommended_for": "TBD",
        "chinese_recommended_for": "待配置 OPENAI_API_KEY 后生成中文推荐人群。",
        "possible_use_cases": "TBD",
        "chinese_possible_use_cases": "待配置 OPENAI_API_KEY 后生成中文使用场景。",
        "stars": repo.get("stars", 0),
        "url": repo.get("url", ""),
    }


def _get_openai_api_key() -> str | None:
    """Load OPENAI_API_KEY from .env or the process environment."""
    load_dotenv()
    return os.getenv("OPENAI_API_KEY")


def _select_repositories_with_local_score(
    repos: list[dict[str, Any]],
    top_k: int,
) -> list[dict[str, Any]]:
    """Select repositories with deterministic keyword and popularity scoring."""
    scored_repos = [
        (_score_repository_value(repo), index, repo)
        for index, repo in enumerate(repos)
    ]
    scored_repos.sort(key=lambda item: (-item[0], item[1]))
    return [repo for _, _, repo in scored_repos[:top_k]]


def _score_repository_value(repo: dict[str, Any]) -> int:
    """Score one repository by AI relevance and GitHub stars."""
    name = str(repo.get("name", "")).lower()
    description = str(repo.get("description", "")).lower()
    language = str(repo.get("language", "")).lower()
    keywords = [keyword.lower() for keyword in AI_KEYWORDS]
    keywords.extend(["llm", "agent", "rag", "transformer", "machine learning"])

    score = min(int(repo.get("stars") or 0), 100_000) // 100
    for keyword in keywords:
        if keyword in name:
            score += 8
        if keyword in description:
            score += 4
        if keyword in language:
            score += 1

    return score


def _select_repositories_with_openai(
    repos: list[dict[str, Any]],
    top_k: int,
    api_key: str,
) -> list[dict[str, Any]]:
    """Use OpenAI to select the most valuable candidate repositories."""
    model = os.getenv("OPENAI_GITHUB_SELECTION_MODEL", OPENAI_GITHUB_SELECTION_MODEL)
    candidates = [
        {
            "index": index,
            "name": repo.get("name", ""),
            "description": repo.get("description", ""),
            "stars": repo.get("stars", 0),
            "language": repo.get("language", ""),
            "topics": repo.get("topics", []),
            "url": repo.get("url", ""),
        }
        for index, repo in enumerate(repos)
    ]
    prompt = _format_prompt_template(
        filename="github_selection_prompt.txt",
        fallback=GITHUB_SELECTION_PROMPT_FALLBACK,
        top_k=top_k,
        repos=json.dumps(candidates, ensure_ascii=False),
    )

    try:
        data = _call_openai_json(
            api_key=api_key,
            model=model,
            system_message="You are an AI open-source project analyst.",
            user_message=prompt,
        )
        selected_indices = data.get("selected_indices", [])
        selected_repos = []
        for index in selected_indices:
            if isinstance(index, int) and 0 <= index < len(repos):
                selected_repos.append(repos[index])
            if len(selected_repos) >= top_k:
                break
        return selected_repos
    except Exception as error:
        print(f"Failed to select GitHub repositories with OpenAI: {error}")
        return []


def _summarize_repository_with_openai(
    repo: dict[str, Any],
    api_key: str,
) -> dict[str, Any] | None:
    """Use OpenAI to generate a structured repository summary."""
    model = os.getenv("OPENAI_GITHUB_SUMMARY_MODEL", OPENAI_GITHUB_SUMMARY_MODEL)
    readme_excerpt = fetch_repository_readme(str(repo.get("name", "")))
    prompt = _format_prompt_template(
        filename="github_summary_prompt.txt",
        fallback=GITHUB_SUMMARY_PROMPT_FALLBACK,
        name=repo.get("name", "Unnamed repository"),
        description=repo.get("description", ""),
        stars=repo.get("stars", 0),
        language=repo.get("language", ""),
        topics=", ".join(repo.get("topics", [])) if repo.get("topics") else "None",
        homepage=repo.get("homepage", ""),
        license=repo.get("license", ""),
        url=repo.get("url", ""),
        readme_excerpt=readme_excerpt or "No README excerpt available.",
    )

    try:
        data = _call_openai_json(
            api_key=api_key,
            model=model,
            system_message="You are an AI engineering assistant that writes concise structured repository summaries.",
            user_message=prompt,
        )
    except Exception as error:
        print(f"Failed to summarize GitHub repository with OpenAI: {error}")
        return None

    summary = {}
    for field in GITHUB_SUMMARY_FIELDS:
        value = data.get(field)
        if isinstance(value, str) and value.strip():
            summary[field] = value.strip()

    return summary or None


def _format_prompt_template(
    filename: str,
    fallback: str,
    **values: Any,
) -> str:
    """Load a prompt template and format it with a fallback on any failure."""
    template = _load_prompt_template(filename, fallback)
    try:
        return template.format(**values)
    except Exception as error:
        print(f"Failed to format prompt template {filename}: {error}")
        return fallback.format(**values)


def _load_prompt_template(filename: str, fallback: str) -> str:
    """Load a prompt template from prompts/, falling back to an inline template."""
    prompt_path = BASE_DIR / "prompts" / filename
    try:
        template = prompt_path.read_text(encoding="utf-8").strip()
        return template or fallback
    except OSError as error:
        print(f"Failed to load prompt template {filename}: {error}")
        return fallback


def _merge_repository_summary(
    repo: dict[str, Any],
    generated_summary: dict[str, Any],
) -> dict[str, Any]:
    """Merge an LLM-generated summary with stable repository metadata."""
    description = str(
        repo.get("description", "Repository summary will be generated by the LLM.")
    )
    merged = {
        "name": str(repo.get("name", "Unnamed repository")),
        "one_sentence_summary": description,
        "chinese_summary": generated_summary.get(
            "chinese_summary",
            GITHUB_SUMMARY_FALLBACK,
        ),
        "main_features": description or "TBD",
        "chinese_main_features": generated_summary.get("chinese_main_features", "待补充"),
        "technical_highlights": "TBD",
        "chinese_technical_highlights": generated_summary.get(
            "chinese_technical_highlights",
            "待补充",
        ),
        "learning_value": "TBD",
        "chinese_learning_value": generated_summary.get("chinese_learning_value", "待补充"),
        "recommended_for": "TBD",
        "chinese_recommended_for": generated_summary.get("chinese_recommended_for", "待补充"),
        "possible_use_cases": "TBD",
        "chinese_possible_use_cases": generated_summary.get(
            "chinese_possible_use_cases",
            "待补充",
        ),
        "stars": repo.get("stars", 0),
        "url": repo.get("url", ""),
    }
    merged.update(generated_summary)
    return merged


def _call_openai_json(
    api_key: str,
    model: str,
    system_message: str,
    user_message: str,
) -> dict[str, Any]:
    """Call OpenAI Chat Completions and parse a JSON object response."""
    from openai import OpenAI

    client = OpenAI(api_key=api_key)
    completion = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system_message},
            {"role": "user", "content": user_message},
        ],
        response_format={"type": "json_object"},
        temperature=0.2,
    )
    content = completion.choices[0].message.content
    if not content:
        raise ValueError("OpenAI returned an empty JSON response.")
    parsed = json.loads(content)
    if not isinstance(parsed, dict):
        raise ValueError("OpenAI JSON response was not an object.")
    return parsed
