"""Repository selection and summarization placeholders for the MVP skeleton."""

from typing import Any


def select_important_repositories(
    repos: list[dict[str, Any]],
    top_k: int = 3,
) -> list[dict[str, Any]]:
    """Select the first `top_k` repositories until LLM ranking is implemented."""
    return repos[:top_k]


def summarize_repository(repo: dict[str, Any]) -> dict[str, Any]:
    """Return a structured placeholder summary for one repository."""
    name = str(repo.get("name", "Unnamed repository"))
    description = str(
        repo.get("description", "Repository summary will be generated by the LLM.")
    )

    return {
        "name": name,
        "one_sentence_summary": description,
        "main_features": "TBD",
        "technical_highlights": "TBD",
        "learning_value": "TBD",
        "recommended_for": "TBD",
        "possible_use_cases": "TBD",
        "stars": repo.get("stars", 0),
        "url": repo.get("url", ""),
    }
