"""AI news selection and summarization helpers."""

import json
import os
from typing import Any

from dotenv import load_dotenv

from config import (
    BASE_DIR,
    OPENAI_NEWS_SELECTION_MODEL,
    OPENAI_NEWS_SUMMARY_MODEL,
)


NEWS_SUMMARY_FALLBACK = "待配置 OPENAI_API_KEY 后生成新闻中文摘要。"
NEWS_SUMMARY_FIELDS = [
    "one_sentence_summary",
    "chinese_summary",
    "what_happened",
    "chinese_what_happened",
    "why_it_matters",
    "chinese_why_it_matters",
    "impact",
    "chinese_impact",
    "related_technologies",
    "chinese_related_technologies",
]
NEWS_KEYWORDS = [
    "llm",
    "agent",
    "rag",
    "multimodal",
    "reasoning",
    "model release",
    "api",
    "developer",
    "benchmark",
    "open source",
    "research",
    "safety",
    "security",
    "product",
]
NEWS_SELECTION_PROMPT_FALLBACK = (
    "Select the top AI industry news items for a daily intelligence report.\n"
    "Prioritize company announcements, model releases, developer tools, safety "
    "updates, research releases, API changes, and items that matter to AI "
    "developers or researchers.\n"
    "Return JSON only with this schema: {{\"selected_indices\": [0, 1]}}.\n"
    "Select at most {top_k} news items.\n\n"
    "Candidate news:\n{news_items}"
)
NEWS_SUMMARY_PROMPT_FALLBACK = (
    "Summarize this AI industry news item for developers and AI learners.\n"
    "Return JSON only with these string fields:\n"
    "one_sentence_summary, chinese_summary, what_happened, chinese_what_happened, "
    "why_it_matters, chinese_why_it_matters, impact, chinese_impact, "
    "related_technologies, chinese_related_technologies.\n"
    "Chinese fields should be natural Simplified Chinese sentences. Keep company "
    "names, product names, model names, API names, URLs, and common AI terms such "
    "as LLM, RAG, RL, VLM, Transformer in English when that is clearer.\n\n"
    "Title: {title}\n"
    "Source: {source}\n"
    "Published: {published_date}\n"
    "URL: {url}\n\n"
    "Summary or excerpt:\n{summary}"
)


def select_important_news(
    news_items: list[dict[str, Any]],
    top_k: int = 3,
) -> list[dict[str, Any]]:
    """Select the most useful news items for the daily report."""
    if not news_items or top_k <= 0:
        return []

    api_key = _get_openai_api_key()
    if api_key:
        selected_news = _select_news_with_openai(news_items, top_k, api_key)
        if selected_news:
            return selected_news

    return _select_news_with_keyword_score(news_items, top_k)


def summarize_news_item(news_item: dict[str, Any]) -> dict[str, Any]:
    """Return a structured summary for one news item."""
    title = str(news_item.get("title", "Untitled news"))
    source_summary = str(news_item.get("summary", "News summary will be generated by the LLM."))

    api_key = _get_openai_api_key()
    if api_key:
        llm_summary = _summarize_news_with_openai(news_item, api_key)
        if llm_summary:
            return _merge_news_summary(news_item, llm_summary)

    return {
        "title": title,
        "source": news_item.get("source", ""),
        "one_sentence_summary": source_summary,
        "chinese_summary": NEWS_SUMMARY_FALLBACK,
        "what_happened": source_summary or "TBD",
        "chinese_what_happened": "待配置 OPENAI_API_KEY 后生成中文事件概述。",
        "why_it_matters": "TBD",
        "chinese_why_it_matters": "待配置 OPENAI_API_KEY 后生成中文重要性。",
        "impact": "TBD",
        "chinese_impact": "待配置 OPENAI_API_KEY 后生成中文影响。",
        "related_technologies": "TBD",
        "chinese_related_technologies": "待配置 OPENAI_API_KEY 后生成中文相关技术。",
        "url": news_item.get("url", ""),
    }


def summarize_news_items(news_items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Return structured summaries for a list of news items."""
    return [summarize_news_item(news_item) for news_item in news_items]


def _get_openai_api_key() -> str | None:
    """Load OPENAI_API_KEY from .env or the process environment."""
    load_dotenv()
    return os.getenv("OPENAI_API_KEY")


def _select_news_with_keyword_score(
    news_items: list[dict[str, Any]],
    top_k: int,
) -> list[dict[str, Any]]:
    """Select news with deterministic keyword scoring."""
    scored_news = [
        (_score_news_relevance(news_item), index, news_item)
        for index, news_item in enumerate(news_items)
    ]
    if not any(score > 0 for score, _, _ in scored_news):
        return news_items[:top_k]
    scored_news.sort(key=lambda item: (-item[0], item[1]))
    return [news_item for _, _, news_item in scored_news[:top_k]]


def _score_news_relevance(news_item: dict[str, Any]) -> int:
    """Score one news item by title and summary keyword relevance."""
    title = str(news_item.get("title", "")).lower()
    summary = str(news_item.get("summary", "")).lower()
    source = str(news_item.get("source", "")).lower()

    score = 0
    for keyword in NEWS_KEYWORDS:
        if keyword in title:
            score += 3
        if keyword in summary:
            score += 1
        if keyword in source:
            score += 1
    return score


def _select_news_with_openai(
    news_items: list[dict[str, Any]],
    top_k: int,
    api_key: str,
) -> list[dict[str, Any]]:
    """Use OpenAI to select the most important news items."""
    model = os.getenv("OPENAI_NEWS_SELECTION_MODEL", OPENAI_NEWS_SELECTION_MODEL)
    candidates = [
        {
            "index": index,
            "title": news_item.get("title", ""),
            "source": news_item.get("source", ""),
            "summary": news_item.get("summary", ""),
            "published_date": news_item.get("published_date", ""),
            "url": news_item.get("url", ""),
        }
        for index, news_item in enumerate(news_items)
    ]
    prompt = _format_prompt_template(
        filename="news_selection_prompt.txt",
        fallback=NEWS_SELECTION_PROMPT_FALLBACK,
        top_k=top_k,
        news_items=json.dumps(candidates, ensure_ascii=False),
    )

    try:
        data = _call_openai_json(
            api_key=api_key,
            model=model,
            system_message="You are an AI industry intelligence analyst.",
            user_message=prompt,
        )
        selected_indices = data.get("selected_indices", [])
        selected_news = []
        for index in selected_indices:
            if isinstance(index, int) and 0 <= index < len(news_items):
                selected_news.append(news_items[index])
            if len(selected_news) >= top_k:
                break
        return selected_news
    except Exception as error:
        print(f"Failed to select news with OpenAI: {error}")
        return []


def _summarize_news_with_openai(
    news_item: dict[str, Any],
    api_key: str,
) -> dict[str, Any] | None:
    """Use OpenAI to generate a structured news summary."""
    model = os.getenv("OPENAI_NEWS_SUMMARY_MODEL", OPENAI_NEWS_SUMMARY_MODEL)
    prompt = _format_prompt_template(
        filename="news_summary_prompt.txt",
        fallback=NEWS_SUMMARY_PROMPT_FALLBACK,
        title=news_item.get("title", "Untitled news"),
        source=news_item.get("source", ""),
        published_date=news_item.get("published_date", ""),
        url=news_item.get("url", ""),
        summary=news_item.get("summary", ""),
    )

    try:
        data = _call_openai_json(
            api_key=api_key,
            model=model,
            system_message="You are an AI news analyst that writes concise structured summaries.",
            user_message=prompt,
        )
    except Exception as error:
        print(f"Failed to summarize news with OpenAI: {error}")
        return None

    summary = {}
    for field in NEWS_SUMMARY_FIELDS:
        value = data.get(field)
        if isinstance(value, str) and value.strip():
            summary[field] = value.strip()
    return summary or None


def _merge_news_summary(
    news_item: dict[str, Any],
    generated_summary: dict[str, Any],
) -> dict[str, Any]:
    """Merge an LLM-generated news summary with stable source metadata."""
    source_summary = str(news_item.get("summary", "News summary will be generated by the LLM."))
    merged = {
        "title": str(news_item.get("title", "Untitled news")),
        "source": news_item.get("source", ""),
        "one_sentence_summary": source_summary,
        "chinese_summary": generated_summary.get("chinese_summary", NEWS_SUMMARY_FALLBACK),
        "what_happened": source_summary or "TBD",
        "chinese_what_happened": generated_summary.get("chinese_what_happened", "待补充"),
        "why_it_matters": "TBD",
        "chinese_why_it_matters": generated_summary.get("chinese_why_it_matters", "待补充"),
        "impact": "TBD",
        "chinese_impact": generated_summary.get("chinese_impact", "待补充"),
        "related_technologies": "TBD",
        "chinese_related_technologies": generated_summary.get(
            "chinese_related_technologies",
            "待补充",
        ),
        "url": news_item.get("url", ""),
    }
    merged.update(generated_summary)
    return merged


def _format_prompt_template(
    filename: str,
    fallback: str,
    **values: Any,
) -> str:
    """Load a prompt template and format it with a fallback on any failure."""
    template = _load_prompt_template(filename, fallback)
    try:
        return template.format(**values)
    except Exception as error:
        print(f"Failed to format prompt template {filename}: {error}")
        return fallback.format(**values)


def _load_prompt_template(filename: str, fallback: str) -> str:
    """Load a prompt template from prompts/, falling back to an inline template."""
    prompt_path = BASE_DIR / "prompts" / filename
    try:
        template = prompt_path.read_text(encoding="utf-8").strip()
        return template or fallback
    except OSError as error:
        print(f"Failed to load prompt template {filename}: {error}")
        return fallback


def _call_openai_json(
    api_key: str,
    model: str,
    system_message: str,
    user_message: str,
) -> dict[str, Any]:
    """Call OpenAI Chat Completions and parse a JSON object response."""
    from openai import OpenAI

    client = OpenAI(api_key=api_key)
    completion = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system_message},
            {"role": "user", "content": user_message},
        ],
        response_format={"type": "json_object"},
        temperature=0.2,
    )
    content = completion.choices[0].message.content
    if not content:
        raise ValueError("OpenAI returned an empty JSON response.")
    parsed = json.loads(content)
    if not isinstance(parsed, dict):
        raise ValueError("OpenAI JSON response was not an object.")
    return parsed
