"""Paper selection and summarization placeholders for the MVP skeleton."""

from typing import Any


def select_important_papers(
    papers: list[dict[str, Any]],
    top_k: int = 3,
) -> list[dict[str, Any]]:
    """Select the first `top_k` papers until LLM ranking is implemented."""
    return papers[:top_k]


def summarize_paper(paper: dict[str, Any]) -> dict[str, Any]:
    """Return a structured placeholder summary for one paper."""
    title = str(paper.get("title", "Untitled paper"))
    summary = str(paper.get("summary", "Summary will be generated by the LLM."))

    return {
        "title": title,
        "one_sentence_summary": summary,
        "research_problem": "TBD",
        "core_method": "TBD",
        "innovation": "TBD",
        "why_it_matters": "TBD",
        "learning_value": "TBD",
        "url": paper.get("url", ""),
    }
