"""Paper selection and summarization helpers."""

import json
import os
from typing import Any

from dotenv import load_dotenv

from config import (
    AI_KEYWORDS,
    OPENAI_PAPER_SELECTION_MODEL,
    OPENAI_PAPER_SUMMARY_MODEL,
    OPENAI_TRANSLATION_MODEL,
)


CHINESE_SUMMARY_FALLBACK = "待配置 OPENAI_API_KEY 后生成中文摘要。"
PAPER_SUMMARY_FIELDS = [
    "one_sentence_summary",
    "chinese_summary",
    "research_problem",
    "core_method",
    "innovation",
    "why_it_matters",
    "learning_value",
]


def select_important_papers(
    papers: list[dict[str, Any]],
    top_k: int = 3,
) -> list[dict[str, Any]]:
    """Select the most useful papers for the daily report."""
    if not papers or top_k <= 0:
        return []

    api_key = _get_openai_api_key()
    if api_key:
        selected_papers = _select_papers_with_openai(papers, top_k, api_key)
        if selected_papers:
            return selected_papers

    return _select_papers_with_keyword_score(papers, top_k)


def summarize_paper(paper: dict[str, Any]) -> dict[str, Any]:
    """Return a structured summary for one paper."""
    title = str(paper.get("title", "Untitled paper"))
    summary = str(paper.get("summary", "Summary will be generated by the LLM."))

    api_key = _get_openai_api_key()
    if api_key:
        llm_summary = _summarize_paper_with_openai(paper, api_key)
        if llm_summary:
            return _merge_paper_summary(paper, llm_summary)

    return {
        "title": title,
        "one_sentence_summary": summary,
        "chinese_summary": _translate_text_to_chinese(summary),
        "research_problem": "TBD",
        "core_method": "TBD",
        "innovation": "TBD",
        "why_it_matters": "TBD",
        "learning_value": "TBD",
        "url": paper.get("url", ""),
    }


def _get_openai_api_key() -> str | None:
    """Load OPENAI_API_KEY from .env or the process environment."""
    load_dotenv()
    return os.getenv("OPENAI_API_KEY")


def _select_papers_with_keyword_score(
    papers: list[dict[str, Any]],
    top_k: int,
) -> list[dict[str, Any]]:
    """Select papers with a deterministic local AI-keyword relevance score."""
    scored_papers = [
        (_score_paper_relevance(paper), index, paper)
        for index, paper in enumerate(papers)
    ]

    if not any(score > 0 for score, _, _ in scored_papers):
        return papers[:top_k]

    scored_papers.sort(key=lambda item: (-item[0], item[1]))
    return [paper for _, _, paper in scored_papers[:top_k]]


def _score_paper_relevance(paper: dict[str, Any]) -> int:
    """Score one paper by how strongly its title and abstract match AI topics."""
    title = str(paper.get("title", "")).lower()
    summary = str(paper.get("summary", "")).lower()
    keywords = [keyword.lower() for keyword in AI_KEYWORDS]
    keywords.extend(["llm", "agent", "rag", "transformer", "machine learning"])

    score = 0
    for keyword in keywords:
        if keyword in title:
            score += 3
        if keyword in summary:
            score += 1

    return score


def _select_papers_with_openai(
    papers: list[dict[str, Any]],
    top_k: int,
    api_key: str,
) -> list[dict[str, Any]]:
    """Use OpenAI to select the most valuable candidate papers."""
    model = os.getenv("OPENAI_PAPER_SELECTION_MODEL", OPENAI_PAPER_SELECTION_MODEL)
    candidates = [
        {
            "index": index,
            "title": paper.get("title", ""),
            "summary": paper.get("summary", ""),
            "url": paper.get("url", ""),
        }
        for index, paper in enumerate(papers)
    ]
    prompt = (
        "Select the top AI research papers for a daily intelligence report.\n"
        "Prioritize relevance to LLMs, AI agents, RAG, multimodal AI, AI coding, "
        "reasoning, machine learning systems, novelty, impact, and learning value.\n"
        f"Return JSON only with this schema: {{\"selected_indices\": [0, 1]}}.\n"
        f"Select at most {top_k} papers.\n\n"
        f"Candidate papers:\n{json.dumps(candidates, ensure_ascii=False)}"
    )

    try:
        data = _call_openai_json(
            api_key=api_key,
            model=model,
            system_message="You are an AI research intelligence analyst.",
            user_message=prompt,
        )
        selected_indices = data.get("selected_indices", [])
        selected_papers = []
        for index in selected_indices:
            if isinstance(index, int) and 0 <= index < len(papers):
                selected_papers.append(papers[index])
            if len(selected_papers) >= top_k:
                break
        return selected_papers
    except Exception as error:
        print(f"Failed to select papers with OpenAI: {error}")
        return []


def _summarize_paper_with_openai(
    paper: dict[str, Any],
    api_key: str,
) -> dict[str, Any] | None:
    """Use OpenAI to generate a structured paper summary."""
    model = os.getenv("OPENAI_PAPER_SUMMARY_MODEL", OPENAI_PAPER_SUMMARY_MODEL)
    title = str(paper.get("title", "Untitled paper"))
    abstract = str(paper.get("summary", ""))
    prompt = (
        "Summarize this AI research paper for developers and AI learners.\n"
        "Return JSON only with these string fields:\n"
        "one_sentence_summary, chinese_summary, research_problem, core_method, "
        "innovation, why_it_matters, learning_value.\n\n"
        f"Title: {title}\n\n"
        f"Abstract: {abstract}"
    )

    try:
        data = _call_openai_json(
            api_key=api_key,
            model=model,
            system_message="You are an AI research assistant that writes concise structured summaries.",
            user_message=prompt,
        )
    except Exception as error:
        print(f"Failed to summarize paper with OpenAI: {error}")
        return None

    summary = {}
    for field in PAPER_SUMMARY_FIELDS:
        value = data.get(field)
        if isinstance(value, str) and value.strip():
            summary[field] = value.strip()

    return summary or None


def _merge_paper_summary(
    paper: dict[str, Any],
    generated_summary: dict[str, Any],
) -> dict[str, Any]:
    """Merge an LLM-generated summary with stable paper metadata."""
    fallback_summary = str(paper.get("summary", "Summary will be generated by the LLM."))
    chinese_summary = generated_summary.get("chinese_summary")
    if not isinstance(chinese_summary, str) or not chinese_summary.strip():
        chinese_summary = _translate_text_to_chinese(fallback_summary)

    merged = {
        "title": str(paper.get("title", "Untitled paper")),
        "one_sentence_summary": fallback_summary,
        "chinese_summary": chinese_summary,
        "research_problem": "TBD",
        "core_method": "TBD",
        "innovation": "TBD",
        "why_it_matters": "TBD",
        "learning_value": "TBD",
        "url": paper.get("url", ""),
    }
    merged.update(generated_summary)
    return merged


def _call_openai_json(
    api_key: str,
    model: str,
    system_message: str,
    user_message: str,
) -> dict[str, Any]:
    """Call OpenAI Chat Completions and parse a JSON object response."""
    from openai import OpenAI

    client = OpenAI(api_key=api_key)
    completion = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system_message},
            {"role": "user", "content": user_message},
        ],
        response_format={"type": "json_object"},
        temperature=0.2,
    )
    content = completion.choices[0].message.content
    if not content:
        raise ValueError("OpenAI returned an empty JSON response.")
    parsed = json.loads(content)
    if not isinstance(parsed, dict):
        raise ValueError("OpenAI JSON response was not an object.")
    return parsed


def _translate_text_to_chinese(text: str) -> str:
    """Translate English text into concise Chinese using OpenAI when configured."""
    source_text = text.strip()
    if not source_text:
        return "待补充"

    api_key = _get_openai_api_key()
    if not api_key:
        return CHINESE_SUMMARY_FALLBACK

    model = os.getenv("OPENAI_TRANSLATION_MODEL", OPENAI_TRANSLATION_MODEL)

    try:
        from openai import OpenAI

        client = OpenAI(api_key=api_key)
        completion = client.chat.completions.create(
            model=model,
            messages=[
                {
                    "role": "system",
                    "content": "You translate AI research paper abstracts into clear, concise Simplified Chinese.",
                },
                {
                    "role": "user",
                    "content": (
                        "请将下面的论文摘要翻译成简洁、准确的中文。"
                        "只输出中文译文，不要添加额外说明。\n\n"
                        f"{source_text}"
                    ),
                },
            ],
            temperature=0.2,
        )
        translated_text = completion.choices[0].message.content
        if translated_text:
            return translated_text.strip()
    except Exception as error:
        print(f"Failed to translate paper summary: {error}")

    return CHINESE_SUMMARY_FALLBACK
