"""Paper selection and summarization helpers."""

import os
from typing import Any

from dotenv import load_dotenv

from config import OPENAI_TRANSLATION_MODEL


CHINESE_SUMMARY_FALLBACK = "待配置 OPENAI_API_KEY 后生成中文摘要。"


def select_important_papers(
    papers: list[dict[str, Any]],
    top_k: int = 3,
) -> list[dict[str, Any]]:
    """Select the first `top_k` papers until LLM ranking is implemented."""
    return papers[:top_k]


def summarize_paper(paper: dict[str, Any]) -> dict[str, Any]:
    """Return a structured summary for one paper."""
    title = str(paper.get("title", "Untitled paper"))
    summary = str(paper.get("summary", "Summary will be generated by the LLM."))

    return {
        "title": title,
        "one_sentence_summary": summary,
        "chinese_summary": _translate_text_to_chinese(summary),
        "research_problem": "TBD",
        "core_method": "TBD",
        "innovation": "TBD",
        "why_it_matters": "TBD",
        "learning_value": "TBD",
        "url": paper.get("url", ""),
    }


def _translate_text_to_chinese(text: str) -> str:
    """Translate English text into concise Chinese using OpenAI when configured."""
    source_text = text.strip()
    if not source_text:
        return "待补充"

    load_dotenv()
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        return CHINESE_SUMMARY_FALLBACK

    model = os.getenv("OPENAI_TRANSLATION_MODEL", OPENAI_TRANSLATION_MODEL)

    try:
        from openai import OpenAI

        client = OpenAI(api_key=api_key)
        completion = client.chat.completions.create(
            model=model,
            messages=[
                {
                    "role": "system",
                    "content": "You translate AI research paper abstracts into clear, concise Simplified Chinese.",
                },
                {
                    "role": "user",
                    "content": (
                        "请将下面的论文摘要翻译成简洁、准确的中文。"
                        "只输出中文译文，不要添加额外说明。\n\n"
                        f"{source_text}"
                    ),
                },
            ],
            temperature=0.2,
        )
        translated_text = completion.choices[0].message.content
        if translated_text:
            return translated_text.strip()
    except Exception as error:
        print(f"Failed to translate paper summary: {error}")

    return CHINESE_SUMMARY_FALLBACK
